import type { Metadata } from "next";
import "../../styles/globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <a href="#">Test</a>
            </li>
            <li>
              <a href="#">ALso Test</a>
            </li>
            <li>
              <a href="#">Umm...</a>
            </li>
            <li>
              <a href="#">Coffee?</a>
            </li>
            <li>
              <a href="#">No ok Ill just go over here...</a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
